### ISSUE TITLE
No NuGet package

### ISSUE THREAD

**Issue by SamuelEnglard** [fuzzykiller/progress-hierarchy#1]
I'd love to use this in my project but I would prefer to only include NuGet packages

**Comment by fuzzykiller** [comment]
Providing a NuGet package is the general idea, however the code isn’t ready yet.

Also, I’m still struggling with AppVeyor.

**Comment by SamuelEnglard** [comment]
Ah, fair enough. Can't wait!

**Comment by fuzzykiller** [comment]
Although my efforts to further unit testing hit a snag (see #2), the NuGet package is now available: https://www.nuget.org/packages/ConsoleProgressBar/
