### ISSUE TITLE
Make ProgressBar.CreateStatusText(IReadOnlyList<string>,int) virtual

### ISSUE THREAD

**Issue by SamuelEnglard** [fuzzykiller/progress-hierarchy#3]
For example I want each status to be on a separate line but I can't do that without overriding `ProgressBar.CreateStatusText(IReadOnlyList<string>,int)` which isn't virtual

**Comment by fuzzykiller** [comment]
Hi, I'll consider it. I'm currently on vacation though. Of course you could also create a pull request. 😃

**Comment by fuzzykiller** [comment]
\[Several years later…\]

This is now solved in version 2.0 which will soon be published. YMMV though due to console scrolling.
