### ISSUE TITLE
ArgumentOutOfRangeException at System.ConsolePal.SetCursorPosition()

### ISSUE THREAD

**Issue by mganss** [fuzzykiller/progress-hierarchy#4]
When using the progress bar in addition to (lots of) other output to the console I came across this:

```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 58.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at ConsoleProgressBar.ProgressBar.Dispose(Boolean disposing)
   at ConsoleProgressBar.ProgressBar.Dispose()
```

I assume during disposal it tries to remove the progress bar but since it has already scrolled out of view this exception occurs.

**Comment by fuzzykiller** [comment]
It was never designed for concurrent use with other console output. For the moment, I’d recommend deriving from `ProgressBar` and overriding the dispose logic so it doesn’t call `SetCursorPosition`.

I’ll probably add a flag like `leaveOpen` on `StreamWriter` so it’ll just leave the cursor alone on `Dispose`.

**Comment by mganss** [comment]
Environment variables are the same. Perhaps it has to do with Windows Terminal 🤷🏻‍♂️
